services:
    reverse-proxy:
        container_name: reverse-proxy
        image: sikhoo0/reverse-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/www/letsencrypt:/var/www/letsencrypt
        restart: unless-stopped
        depends_on:
            - app

    app:
        container_name: app
        image: sikhoo0/app
        restart: always
        environment:
            - NODE_ENV=production
            - APP_HOST=${APP_HOST}
            - APP_PORT=${APP_PORT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_USER=${DB_USER}
            - DB_PW=${DB_PW}
            - DB_NAME=${DB_NAME}
            - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
            - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
            - ACCESS_TOKEN_EXPIRY_TIME=${ACCESS_TOKEN_EXPIRY_TIME}
            - REFRESH_TOKEN_EXPIRY_TIME=${REFRESH_TOKEN_EXPIRY_TIME}
