services:
    app:
        build:
            context: ..
            dockerfile: ../Dockerfile
        ports:
            - 3000:${APP_PORT}
        environment:
            - NODE_ENV=production
            - APP_PORT=${APP_PORT}
